spring:
  application:
    name: labweb_be

  datasource:
    url: jdbc:mariadb://${MARIA_HOST}:${MARIA_PORT}/${MARIA_DATABASE}
    username: ${MARIA_USER}
    password: ${MARIA_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


logging:
  level:
    org.springframework:
      transaction.interceptor: trace    # 트랜잭션 로그 설정

    p6spy: info


# P6Spy Configuration
decorator:
  datasource:
    p6spy:
      enable-logging: true